### ISSUE TITLE
Invalid option in transform() call: "tsconfig"

### ISSUE THREAD

**Issue by IlyaSemenov** [galvez/nuxt-esbuild-module#2]
The documentation mentions option `esbuild.tsconfig`:

https://github.com/galvez/nuxt-esbuild-module/blob/1fac7e2afffae0a2eda696643545b52653ed5dac/README.md#L36-L40

However there is no such option in esbuild transform API:

```
Module build failed (from ./node_modules/esbuild-loader/dist/index.js):                                                                                                        friendly-errors 18:19:20
Error: Transform failed with 1 error:
/Users/semenov/work/eg11/eg11-web/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:239:12: error: Invalid option in transform() call: "tsconfig"
    at failureErrorWithLog (/Users/semenov/work/eg11/eg11-web/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1443:15)
    at /Users/semenov/work/eg11/eg11-web/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:1288:20
    at /Users/semenov/work/eg11/eg11-web/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:606:9
    at handleIncomingPacket (/Users/semenov/work/eg11/eg11-web/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:703:9)
    at Socket.readFromStdout (/Users/semenov/work/eg11/eg11-web/node_modules/esbuild-loader/node_modules/esbuild/lib/main.js:573:7)
```

The actual option is [`tsconfigRaw`](https://github.com/privatenumber/esbuild-loader/tree/9b9b18a820d3f2d5775e95e7d62fb03b44397b6d#configuration).

**Comment by arkhamvm** [comment]
Got same error. @IlyaSemenov did you solve it?
